server:
    session-timeout: 3600
    port: 9999
    servlet:
      context-path: /datasource

logging:
  level:
     ROOT: info

spring:
    profiles:
      active: pgsql


mybatis:
    mapper-locations: mapper/**/*Mapper.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  export-temp: export/temp
