spring:
    datasource:
        default:
            driverClassName: org.postgresql.Driver
            jdbcUrl: jdbc:postgresql://localhost:5432/postgres
            username: postgres
            password: shootercheng
        testds:
            driverClassName: org.postgresql.Driver
            jdbcUrl: jdbc:postgresql://localhost:5432/postgres
            username: postgres
            password: shootercheng
            template: postgres:db-code
            dburl: postgres
