server:
    session-timeout: 3600
    port: 9999
    servlet:
      context-path: /datasource

logging:
  config: classpath:logback-boot.xml

spring:
    profiles:
      active: mysql


mybatis:
    mapper-locations: mapper/**/*Mapper.xml
    configuration:
      log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

file:
  export-temp: export/temp

header:
  database-key: db-code

pool:
  async:
    corePoolSize: 5
    maximumPoolSize: 8
    keepAliveTime: 1
    timeUnit: MINUTES
    blockingQueue: 2000
