DROP DATABASE IF EXISTS test1;
DROP DATABASE IF EXISTS test2;
CREATE DATABASE test1 charset=utf8mb4;
CREATE DATABASE test2 charset=utf8mb4;

DROP DATABASE IF EXISTS dev_1;
DROP DATABASE IF EXISTS dev_2;
CREATE DATABASE dev_1 charset=utf8mb4;
CREATE DATABASE dev_2 charset=utf8mb4;